UniqloMVC/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using UniqloBL.Services.Abstractions;
using UniqloBL.Services.Concretes;
using UniqloDAL.Models;

namespace UniqloMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        readonly ICategoryService _categoryService;
        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Category> categories = await _categoryService.GetAllCategoriesAsync();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(category);
            //}
            await _categoryService.CreateCategoryAsync(category);
            return RedirectToAction("Index","Categories");
        }

        public async Task<IActionResult> Update(int Id)
        {
            Category sliderItem = await _categoryService.GetCategoryByIdAsync(Id);
            if (sliderItem == null)
            {
                return NotFound("Something went wrong");
            }
            return View(sliderItem);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Category updatedCategoryItem)
        {
            Category currentItem = await _categoryService.GetCategoryByIdAsync(updatedCategoryItem.Id);
            //if (!ModelState.IsValid)
            //{
            //    return BadRequest("Something went wrong");
            //}
            if (currentItem == null)
            {
                return NotFound("Something went wrong");
            }
            await _categoryService.EditCategoryAsync(updatedCategoryItem);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int Id)
        {
            Category deletedItem = await _categoryService.GetCategoryByIdAsync(Id);
            if (deletedItem == null)
            {
                return NotFound("Something went wrong");
            }
            await _categoryService.DeleteCategoryAsync(deletedItem);
            return RedirectToAction("Index","Categories");
        }
    }
}

UniqloMVC/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pronia_MVC.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

UniqloMVC/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UniqloBL.Services.Abstractions;
using UniqloDAL.Contexts;
using UniqloDAL.Models;

namespace UniqloMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductsController : Controller
    {
        readonly IProductService _productService;
        readonly ICategoryService _categoryService;
        public ProductsController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Product> categories = await _productService.GetAllProductsAsync();
            return View(categories);
        }
        public async Task<IActionResult> Create()
        {
            IEnumerable<Category> categories = await _categoryService.GetAllCategoriesAsync();
            ViewBag.Categories = new SelectList(categories,"Id","Title");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Product category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            await _productService.CreateProductAsync(category);
            return RedirectToAction("Index","Products");
        }

        public async Task<IActionResult> Update(int Id)
        {
            Product product = await _productService.GetProductByIdAsync(Id);
            if (product == null)
            {
                return NotFound("Something went wrong");
            }
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Product updatedProductItem)
        {
            Product currentItem = await _productService.GetProductByIdAsync(updatedProductItem.Id);
            if (!ModelState.IsValid)
            {
                return BadRequest("Something went wrong");
            }
            if (currentItem == null)
            {
                return NotFound("Something went wrong");
            }
            _productService.EditProductAsync(updatedProductItem);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int Id)
        {
            Product deletedItem = await _productService.GetProductByIdAsync(Id);
            if (deletedItem == null)
            {
                return NotFound("Something went wrong");
            }
            _productService.DeleteProductAsync(deletedItem);
            return RedirectToAction("Index");
        }
    }
}

UniqloMVC/Areas/Admin/Controllers/SliderItemsController.cs
using UniqloDAL.Contexts;
using UniqloDAL.Models;
using Microsoft.AspNetCore.Mvc;
using UniqloBL.Services.Abstractions;

namespace Pronia_MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderItemsController : Controller
    {
        readonly ISliderItemService _sliderItemService;

        public SliderItemsController(ISliderItemService sliderItemService)
        {
            _sliderItemService = sliderItemService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<SliderItem> sliderItems = await _sliderItemService.GetAllSliderItemsAsync();
            return View(sliderItems);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(SliderItem sliderItem)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Something went wrong");
            }
            _sliderItemService.CreateSliderItem(sliderItem);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int Id)
        {
            SliderItem sliderItem =  await _sliderItemService.GetSliderItemAsync(Id);
            if (sliderItem == null)
            {
                return NotFound("Something went wrong");
            }
            return View(sliderItem);
        }

        [HttpPost]
        public async Task<IActionResult> Update(SliderItem updatedSliderItem)
        {
            SliderItem currentItem = await _sliderItemService.GetSliderItemAsync(updatedSliderItem.Id);
            if (!ModelState.IsValid)
            {
                return BadRequest("Something went wrong");
            }
            if (currentItem == null)
            {
                return NotFound("Something went wrong");
            }
            _sliderItemService.UpdateSliderItem(updatedSliderItem);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int Id)
        {
            SliderItem deletedItem = await _sliderItemService.GetSliderItemAsync(Id);
            if (deletedItem == null)
            {
                return NotFound("Something went wrong");
            }
            _sliderItemService.DeleteSliderItem(deletedItem);
            return RedirectToAction("Index");
        }
    }
}

UniqloMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using UniqloBL.Services.Abstractions;
using UniqloDAL.Models;

namespace UniqloMVC.Controllers
{
    public class HomeController : Controller
    {
        readonly ISliderItemService _sliderItemService;

        public HomeController(ISliderItemService sliderItemService)
        {
            _sliderItemService = sliderItemService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<SliderItem> sliderItems= await _sliderItemService.GetAllSliderItemsAsync();
            return View(sliderItems);
        }
    }
}

UniqloMVC/Areas/Admin/Views/Categories/Create.cshtml
@using UniqloDAL.Models;
@model Category;

<div class="container-fluid">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Title</label>
            <input asp-for="Title" type="text" class="form-control">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary text-white">Submit</button>
    </form>
</div>

UniqloMVC/Areas/Admin/Views/Categories/Index.cshtml
@using UniqloDAL.Models;
@model IEnumerable<Category>;

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Categories</h1>

    <a asp-action="Create" asp-controller="Categories" asp-area="Admin">
        <button class="btn btn-success mb-3">
            Create
        </button>
    </a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Is Active</th>
                            <th>Created Date</th>
                            <th>Updated Date</th>
                            <th>Deleted Date</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (Category item in @Model)
                        {
                            <tr>
                                <td>@item.Title</td>
                                <td>@item.isActive</td>
                                <td>@item.CreatedDate</td>
                                <td>@item.UpdatedDate</td>
                                <td>@item.DeletedDate</td>
                                <td>
                                    <a asp-controller="Categories" asp-action="Update" asp-area="Admin" asp-route-id="@item.Id">
                                        <button class="btn btn-warning text-white">Edit</button>
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-danger" asp-controller="Categories" asp-action="Delete" asp-area="Admin" asp-route-id="@item.Id">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

UniqloMVC/Areas/Admin/Views/Categories/Update.cshtml
@using UniqloDAL.Models;
@model Category;

<div class="container-fluid">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Title</label>
            <input asp-for="Title" type="text" class="form-control">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-warning text-white">Create</button>
    </form>
</div>

UniqloMVC/Areas/Admin/Views/Products/Create.cshtml
@using UniqloDAL.Models;
@model Product;

<div class="container-fluid">
    <form method="post">
        <div class="mb-3">
            <label asp-for="ImagePath" class="form-label">ImagePath</label>
            <input asp-for="ImagePath" type="text" class="form-control">
            <span asp-validation-for="ImagePath" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Title</label>
            <input asp-for="Title" type="text" class="form-control">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <input asp-for="Description" type="text" class="form-control">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Price" class="form-label">Price</label>
            <input asp-for="Price" type="text" class="form-control">
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-select" aria-label="Default select example">
            </select>
        </div>
        <button type="submit" class="btn btn-warning text-white">Create</button>
    </form>
</div>

UniqloMVC/Areas/Admin/Views/Products/Index.cshtml
@using UniqloDAL.Models;
@model IEnumerable<Product>;

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Products</h1>

    <a asp-action="Create" asp-controller="Products" asp-area="Admin">
        <button class="btn btn-success mb-3">
            Create
        </button>
    </a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ImagePath</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th>CategoryId</th>
                            <th>is Active</th>
                            <th>CreatedAt</th>
                            <th>UpdatedAt</th>
                            <th>DeletedAt</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (Product item in Model)
                        {
                            <tr>
                                <td>@item.ImagePath</td>
                                <td>@item.Title</td>
                                <td>@item.Description</td>
                                <td>@item.Price</td>
                                <td>@item.CategoryId</td>
                                <td>@item.isActive</td>
                                <td>@item.CreatedDate</td>
                                <td>@item.UpdatedDate</td>
                                <td>@item.DeletedDate</td>
                                <td>
                                    <a asp-controller="Products" asp-action="Update" asp-area="Admin" asp-route-id="@item.Id">
                                        <button class="btn btn-warning">
                                            Update
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a asp-controller="Products" asp-action="Delete" asp-area="Admin" asp-route-id="@item.Id">
                                        <button class="btn btn-danger">
                                            Delete
                                        </button>
                                    </a>
                                </td>
                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

UniqloMVC/Areas/Admin/Views/Products/Update.cshtml
@using UniqloDAL.Models;
@model Category;

<div class="container-fluid">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Title</label>
            <input asp-for="Title" type="text" class="form-control">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-warning text-white">Create</button>
    </form>
</div>

UniqloMVC/Areas/Admin/Views/SliderItems/Create.cshtml
@model UniqloDAL.Models.SliderItem;
<div class="container-fluid">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Slider Item Title</label>
            <input type="text" class="form-control" asp-for="Title">
        </div>
        <div class="mb-3">
            <label asp-for="ImagePath" class="form-label">Slider Item Path</label>
            <input type="text" class="form-control" asp-for="ImagePath">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

UniqloMVC/Areas/Admin/Views/SliderItems/Index.cshtml
@using UniqloDAL.Models;
@model IEnumerable<SliderItem>;

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Services</h1>
    <div class="d-flex justify-content-end mb-2">
        <a asp-area="Admin" asp-controller="SliderItems" asp-action="Create">
            <button class="btn btn-success">Add Services</button>
        </a>
    </div>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Slider Item Title</th>
                            <th>Slider Item Image</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (SliderItem item in Model)
                        {
                            <tr>
                                <td>@item.Title</td>
                                <td>@item.ImagePath</td> 
                                <td class="text-center">
                                    <a asp-area="Admin" asp-controller="SliderItems" asp-action="Edit" asp-route-id="@item.Id">
                                        <button class="btn btn-primary">
                                            <i class="fa-solid fa-pen"></i>
                                        </button>
                                    </a>
                                </td>
                                <td class="text-center">
                                    <a asp-area="Admin" asp-controller="SliderItems" asp-action="Delete" asp-route-id="@item.Id">
                                        <button class="btn btn-danger">
                                            <i class="fa-solid fa-trash"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
            </div>
<!-- End of Main Content -->

UniqloMVC/Areas/Admin/Views/SliderItems/Update.cshtml
@using UniqloDAL.Models
@model SliderItem;
<div class="container-fluid">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Slider Item Title</label>
            <input type="text" class="form-control" asp-for="Title">
        </div>
        <div class="mb-3">
            <label asp-for="ImagePath" class="form-label">Slider Item Path</label>
            <input type="text" class="form-control" asp-for="ImagePath">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>